apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moodtracker-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - moodtracker.yourdomain.com
    secretName: moodtracker-tls-secret
  rules:
  - host: moodtracker.yourdomain.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: moodtracker-backend-svc
            port:
              number: 3000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: moodtracker-frontend-svc
            port:
              number: 80
