apiVersion: v1
kind: Secret
metadata:
  name: moodtracker-backend-secrets
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://<username>:<password>@<cluster>.mongodb.net/?appName=mood-tracker"
  JWT_SECRET: "your-super-secret-jwt-key"
  APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=...;IngestionEndpoint=...;LiveEndpoint=..."
